### ISSUE TITLE
[US01] Como usuário, eu gostaria de me cadastrar para que meus dados de compra fiquem salvos

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#38]
## Descrição da Issue
Como cliente, eu gostaria de me cadastrar para que meus dados de compra fiquem salvos

## Tasks Frontend:
- [x] Página com formulário de cadastro de cliente /usuarios/cadastro
- [x] Página de login e botão de logout
- [x] Serviço de cliente que submete os dados do formulário via POST
- [x] Mensagem de sucesso ou de erro

## Tasks Backend:
- [x] Repository, Service e Controller de usuário
- [x] Servidor de autenticação e autorização
- [x] CRUD de usuário
- [x] Configurar a rota de cadastro de usuário como pública

**Comment by DouglasMonteles** [comment]
Foi criada uma branch com o nome de [us01](https://github.com/UnBArqDsw2022-1/2022.1_G3_Bazar_Frontend/tree/us01) para a implementação desta US e junto também foi criado o componente de tela de login do usuário
