### ISSUE TITLE
[US02] Como usuário, eu gostaria de cadastrar dados de pagamento para facilitar a compra online

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#39]
## Descrição da Issue
Como cliente, eu gostaria de cadastrar dados de pagamento para facilitar a compra online.

## Tasks Frontend:
- [ ] Durante a efetivação da compra, uma das etapas é a forma de pagamento (vai PIX ou em dinheiro vivo)
- [ ] Formulário de etapas, com  a forma de pagamento
- [ ] Mensagem de sucesso ou de erro ao final

## Tasks Backend:
- [ ] Efetivação da venda
- [ ] Repository, Service e Controller de Pedido
- [ ] Classe modelo de Pedido, ItemPedido
- [ ] Mapeamento Objeto-Relacional das classes modelo
- [ ] Configurar a rota de efetivação de pedido como privada, somente usuários autenticados podem acessa-la
