### ISSUE TITLE
[US04] Como cliente, eu gostaria de editar os meus dados da conta para que não ocorra problemas com informações desatualizadas

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#41]
## Descrição da Issue
Como cliente, eu gostaria de editar os meus dados da conta para que não ocorra problemas com informações desatualizadas

## Tasks Frontend:
- [ ] Componente com formulário de atualização de cadastro de usuário /usuarios/atualizar
- [ ] Service de atualização dos dados de usuário
- [ ] Mensagem de sucesso ou erro

## Tasks Backend:
- [ ] Recurso para atualização dos dados de usuário
- [ ] Métodos de atualizar em Repository, Service e Controller de Usuário
- [ ] Configurar a rota de atualização como privada
