### ISSUE TITLE
[US07] Como cliente, desejo avaliar a compra efetuada para dar meu feedback ao vendedor.

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#44]
## Descrição da Issue
Como cliente, desejo avaliar a compra efetuada para dar meu feedback ao vendedor.

## Tasks Frontend:
- [ ] Adicionar na página de pedidos do cliente a função de avaliar a compra efetuada
- [ ] Serviço de cliente que submete os dados do formulário via POST
- [ ] Mensagem de sucesso ou de erro

## Tasks Backend:
- [ ] Método de avaliação de pedido em Repository, Service e Controller de usuário
- [ ] Configurar a rota de avaliação de pedido como privada
