### ISSUE TITLE
[US08] Como cliente, eu gostaria de ver os produtos disponíveis para que eu possa escolher qual comprar

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#45]
## Descrição da Issue
Como cliente, eu gostaria de ver os produtos disponíveis para que eu possa escolher qual comprar

## Tasks Frontend:
- [x] Componente que exibe os produtos cadastrados
- [x] Service de produto que busca os produtos do backend

## Tasks Backend:
- [x] Recurso de listagem de produtos Repository, Service e Controller de produto (com paginação)
- [ ] Configurar a rota de listagem de produtos como pública

**Comment by biancasofia** [comment]
Backend
