### ISSUE TITLE
[US09] Como cliente, eu gostaria de adicionar um produto ao meu carrinho para gerenciar a minha compra

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#46]
## Descrição da Issue
Como cliente, eu gostaria de adicionar um produto ao meu carrinho para gerenciar a minha compra

## Tasks Frontend:
- [x] Método de adição de produto ao carrinho de compras
- [x] Service de produto com método de adição de produto
- [x] Service de LocalStorage para armazenar os dados do carrinho de compra no navegador
