### ISSUE TITLE
[US18] Como vendedor, gostaria de realizar uma ou mais vendas, para que os dados fiquem registrados no sistema.

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#55]
## Descrição da Issue
Como vendedor, gostaria de realizar uma ou mais vendas, para que os dados fiquem registrados no sistema

## Tasks Frontend:
- [x] Adição de itens ao carrinho, finalização de compra, relacionar a compra a um cliente cadastrado ou anônimo

## Tasks Backend:
- [x] Método de realização de pedido em Repository, Service e Controller de usuário com perfil de vendedor
- [x] Configurar a rota de inserção de pedido como privada (somente o usuário logado pode ter acesso)

**Comment by DouglasMonteles** [comment]
Tarefas no backend finalizadas
