### ISSUE TITLE
[US19] Como vendedor, gostaria de poder gerar o recibo (nota fiscal) referente a venda, para poder fornecê-la ao cliente.

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#56]
## Descrição da Issue
Como vendedor, gostaria de poder gerar o recibo (nota fiscal) referente a venda, para poder fornecê-la ao cliente

## Tasks Frontend:
- [ ] No componente de listagem de vendas, adicionar opção de gerar recibo

## Tasks Backend:
- [ ] Método de gerar recibo de pedido em Repository, Service e Controller de pedido
- [ ] Configurar a rota de recibo de pedido como privada
