### ISSUE TITLE
[US20] Como vendedor, desejo realizar o cadastro de um produto para venda e disponibilizar na plataforma

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#57]
## Descrição da Issue
Como vendedor, desejo realizar o cadastro de um produto para venda e disponibilizar na plataforma

## Tasks Frontend:
- [x] Componente com formulário de cadastro de produto

## Tasks Backend:
- [x] Método de inserção de produto em Repository, Service e Controller de produto
- [x] Método em Service para atualizar atributos de Produto
- [x] Configurar a rota de inserção de produto como privada

**Comment by biancasofia** [comment]
Backend e auxiliar no front
