### ISSUE TITLE
CRUD de Cidade e Estado

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#60]
## Descrição da Issue
Implementação do CRUD de Estado e Cidade que estão se relacionando por composição

## Tasks:

- [x]  Implementação das classes de modelo (Java beans)
- [x]  Mapeamento Objeto-Relacional com JPA e Hibernate
- [x]  Repository, Service e Controller de Cidade
- [x]  Repository, Service e Controller de Estado

**Comment by laispa** [comment]
## Descrição da Issue
Implementação do CRUD de Estado e Cidade que estão se relacionando por composição

## Tasks:

- [ ]  Implementação das classes de modelo (Java beans)
- [ ]  Mapeamento Objeto-Relacional com JPA e Hibernate
- [ ]  Repository, Service e Controller de Cidade
- [ ]  Repository, Service e Controller de Estado
