### ISSUE TITLE
Padrão GRASP - Criador

### ISSUE THREAD

**Issue by k3vin-batista** [UnBArqDsw2022-1/2022.1_G3_Bazar#62]
## Descrição da Issue
 Documentar o padrão GRASP criador presente no projeto

## Tasks:
- [x] Definição do padrão criador
- [x] Exemplos do padrão GRASP criador presente no projeto
- [ ] Revisar documento pronto
