### ISSUE TITLE
Padrão GRASP especialista

### ISSUE THREAD

**Issue by k3vin-batista** [UnBArqDsw2022-1/2022.1_G3_Bazar#63]
## Descrição da Issue
Documentar o padrão GRASP especialista presente no projeto

## Tasks:
- [x]  Definição do padrão especialista
- [ ]  Exemplos do padrão GRASP especialista presente no projeto
- [ ]  Revisar documento pronto
