### ISSUE TITLE
Padrão GRASP - Controlador

### ISSUE THREAD

**Issue by k3vin-batista** [UnBArqDsw2022-1/2022.1_G3_Bazar#64]
## Descrição da Issue
Documentar o padrão GRASP controlador presente no projeto

## Tasks:
- [x]  Definição do padrão controlador
    - [x] Introdução @iagoomr 
    - [x] Metodologia @art1505 
    - [x] Bibliografia e Versionamento (todos podem modificar)
- [x]  Exemplos do padrão GRASP controlador presente no projeto
    - [x] Exemplos utilizados no projeto (backend) @DouglasMonteles 
    - [x] Conclusão @EduardoGurgel
    - [x] Bibliografia e Versionamento (todos podem modificar)
- [x]  Revisar documento pronto

**Comment by DouglasMonteles** [comment]
Branch para o documento de GRASP de Controller criada: https://github.com/UnBArqDsw2022-1/2022.1_G3_Bazar/tree/graps/controller

**Comment by DouglasMonteles** [comment]
Exemplos utilizados no projeto (backend)

**Comment by iagoomr** [comment]
Introdução

**Comment by EduardoGurgel** [comment]
Conclusão

**Comment by art1505** [comment]
Metodologia
