### ISSUE TITLE
Padrão GRASP - Alta Coesão

### ISSUE THREAD

**Issue by k3vin-batista** [UnBArqDsw2022-1/2022.1_G3_Bazar#65]
## Descrição da Issue
Documentar o padrão GRASP de alta coesão presente no projeto

## Tasks:
- [ ] Definição do padrão de alta coesão
- [ ] Exemplos do padrão GRASP criador presente no projeto
- [ ] Exemplo Cidade e Estado
- [ ]  Revisar documento pronto
