### ISSUE TITLE
Elaborar iniciativa extra

### ISSUE THREAD

**Issue by laispa** [UnBArqDsw2022-1/2022.1_G3_Bazar#73]
## Iniciativa Extra
Fazer a iniciativa extra desta entrega

# Tasks
- [ ] Gerar a documentação do backend (Swagger)
- [ ] evidenciar GRASP no código
- [ ] evidenciar GoFs no código
- [ ] evolução do backlog
